<?php

namespace Database\Seeders;

use App\Models\DailySchedule;
use Illuminate\Database\Seeder;

class DailyScheduleSeeder extends Seeder
{
    public function run(): void
    {
        DailySchedule::truncate();

        $schedules = [
            ['date' => '2026-04-13', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-05-15', 'event_name' => null, 'group_count' => 50, 'notes' => null],
            ['date' => '2026-08-31', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-03-25', 'event_name' => null, 'group_count' => 43, 'notes' => null],
            ['date' => '2026-02-20', 'event_name' => null, 'group_count' => 51, 'notes' => null],
            ['date' => '2026-06-28', 'event_name' => '理事長杯　決勝', 'group_count' => null, 'notes' => null],
            ['date' => '2026-04-10', 'event_name' => null, 'group_count' => 55, 'notes' => null],
            ['date' => '2026-03-22', 'event_name' => null, 'group_count' => 59, 'notes' => null],
            ['date' => '2026-12-20', 'event_name' => '師走杯', 'group_count' => null, 'notes' => null],
            ['date' => '2026-05-04', 'event_name' => null, 'group_count' => 58, 'notes' => null],
            ['date' => '2026-05-21', 'event_name' => null, 'group_count' => 50, 'notes' => null],
            ['date' => '2026-10-25', 'event_name' => '紅葉杯', 'group_count' => null, 'notes' => null],
            ['date' => '2026-01-07', 'event_name' => null, 'group_count' => 35, 'notes' => null],
            ['date' => '2026-08-10', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-04-01', 'event_name' => null, 'group_count' => 39, 'notes' => null],
            ['date' => '2026-03-17', 'event_name' => null, 'group_count' => 44, 'notes' => null],
            ['date' => '2026-03-16', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-04-15', 'event_name' => null, 'group_count' => 39, 'notes' => null],
            ['date' => '2026-01-11', 'event_name' => null, 'group_count' => 52, 'notes' => null],
            ['date' => '2026-05-05', 'event_name' => '親子ゴルフ大会', 'group_count' => 51, 'notes' => null],
            ['date' => '2026-04-14', 'event_name' => null, 'group_count' => 34, 'notes' => null],
            ['date' => '2026-05-13', 'event_name' => null, 'group_count' => 43, 'notes' => null],
            ['date' => '2026-06-22', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-03-07', 'event_name' => null, 'group_count' => 59, 'notes' => null],
            ['date' => '2026-01-08', 'event_name' => null, 'group_count' => 36, 'notes' => null],
            ['date' => '2026-02-19', 'event_name' => null, 'group_count' => 43, 'notes' => null],
            ['date' => '2026-02-17', 'event_name' => null, 'group_count' => 44, 'notes' => null],
            ['date' => '2026-07-06', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-05-08', 'event_name' => null, 'group_count' => 50, 'notes' => null],
            ['date' => '2026-04-29', 'event_name' => null, 'group_count' => 51, 'notes' => null],
            ['date' => '2026-03-19', 'event_name' => null, 'group_count' => 50, 'notes' => null],
            ['date' => '2026-04-23', 'event_name' => null, 'group_count' => 39, 'notes' => null],
            ['date' => '2026-04-11', 'event_name' => '医師会ゴルフコンペ', 'group_count' => 57, 'notes' => null],
            ['date' => '2026-03-03', 'event_name' => null, 'group_count' => 56, 'notes' => null],
            ['date' => '2026-05-09', 'event_name' => null, 'group_count' => 58, 'notes' => null],
            ['date' => '2026-05-31', 'event_name' => '理事長杯　予選', 'group_count' => 58, 'notes' => null],
            ['date' => '2026-10-19', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-12-21', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-08-03', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-01-10', 'event_name' => null, 'group_count' => 58, 'notes' => null],
            ['date' => '2026-03-09', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-04-30', 'event_name' => null, 'group_count' => 38, 'notes' => null],
            ['date' => '2026-01-03', 'event_name' => '打初杯', 'group_count' => 53, 'notes' => null],
            ['date' => '2026-03-11', 'event_name' => null, 'group_count' => 57, 'notes' => null],
            ['date' => '2026-09-24', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-03-18', 'event_name' => null, 'group_count' => 30, 'notes' => null],
            ['date' => '2026-05-06', 'event_name' => null, 'group_count' => 58, 'notes' => null],
            ['date' => '2026-11-24', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-01-23', 'event_name' => null, 'group_count' => 46, 'notes' => null],
            ['date' => '2026-05-14', 'event_name' => null, 'group_count' => 35, 'notes' => null],
            ['date' => '2026-01-04', 'event_name' => '迎春杯', 'group_count' => 60, 'notes' => null],
            ['date' => '2026-02-23', 'event_name' => null, 'group_count' => 51, 'notes' => null],
            ['date' => '2026-01-18', 'event_name' => '月例杯', 'group_count' => 58, 'notes' => null],
            ['date' => '2026-01-22', 'event_name' => null, 'group_count' => 35, 'notes' => null],
            ['date' => '2026-02-25', 'event_name' => null, 'group_count' => 41, 'notes' => null],
            ['date' => '2026-02-10', 'event_name' => null, 'group_count' => 32, 'notes' => null],
            ['date' => '2026-03-28', 'event_name' => '観桜杯', 'group_count' => 57, 'notes' => null],
            ['date' => '2026-01-01', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-03-10', 'event_name' => null, 'group_count' => 59, 'notes' => null],
            ['date' => '2026-03-08', 'event_name' => null, 'group_count' => 58, 'notes' => null],
            ['date' => '2026-01-29', 'event_name' => null, 'group_count' => 48, 'notes' => null],
            ['date' => '2026-03-02', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-01-13', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-05-19', 'event_name' => null, 'group_count' => 42, 'notes' => null],
            ['date' => '2026-02-21', 'event_name' => null, 'group_count' => 50, 'notes' => null],
            ['date' => '2026-05-10', 'event_name' => null, 'group_count' => 54, 'notes' => null],
            ['date' => '2026-02-08', 'event_name' => null, 'group_count' => 50, 'notes' => null],
            ['date' => '2026-02-03', 'event_name' => null, 'group_count' => 32, 'notes' => null],
            ['date' => '2026-05-30', 'event_name' => '博多大学野球部OB会', 'group_count' => 51, 'notes' => null],
            ['date' => '2026-03-04', 'event_name' => null, 'group_count' => 35, 'notes' => null],
            ['date' => '2026-03-29', 'event_name' => '観桜杯', 'group_count' => 56, 'notes' => null],
            ['date' => '2026-03-13', 'event_name' => null, 'group_count' => 50, 'notes' => null],
            ['date' => '2026-04-20', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-05-20', 'event_name' => null, 'group_count' => 38, 'notes' => null],
            ['date' => '2026-06-29', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-04-28', 'event_name' => null, 'group_count' => 34, 'notes' => null],
            ['date' => '2026-04-06', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-04-24', 'event_name' => null, 'group_count' => 35, 'notes' => null],
            ['date' => '2026-02-07', 'event_name' => null, 'group_count' => 57, 'notes' => null],
            ['date' => '2026-04-25', 'event_name' => 'レディースフレンドリー杯', 'group_count' => 51, 'notes' => null],
            ['date' => '2026-01-21', 'event_name' => null, 'group_count' => 31, 'notes' => null],
            ['date' => '2026-05-12', 'event_name' => null, 'group_count' => 59, 'notes' => null],
            ['date' => '2026-02-27', 'event_name' => null, 'group_count' => 37, 'notes' => null],
            ['date' => '2026-04-02', 'event_name' => null, 'group_count' => 37, 'notes' => null],
            ['date' => '2026-03-27', 'event_name' => null, 'group_count' => 38, 'notes' => null],
            ['date' => '2026-01-19', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-06-15', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-01-30', 'event_name' => null, 'group_count' => 44, 'notes' => null],
            ['date' => '2026-11-15', 'event_name' => '菊花杯', 'group_count' => null, 'notes' => null],
            ['date' => '2026-09-12', 'event_name' => '開場記念杯', 'group_count' => null, 'notes' => null],
            ['date' => '2026-05-17', 'event_name' => 'ゴールドシニア杯', 'group_count' => 58, 'notes' => null],
            ['date' => '2026-06-14', 'event_name' => '理事長杯　予選', 'group_count' => null, 'notes' => null],
            ['date' => '2026-09-13', 'event_name' => '開場記念杯', 'group_count' => null, 'notes' => null],
            ['date' => '2026-04-04', 'event_name' => null, 'group_count' => 53, 'notes' => null],
            ['date' => '2026-12-14', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-02-22', 'event_name' => null, 'group_count' => 53, 'notes' => null],
            ['date' => '2026-08-17', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-09-07', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-01-20', 'event_name' => null, 'group_count' => 32, 'notes' => null],
            ['date' => '2026-01-14', 'event_name' => null, 'group_count' => 37, 'notes' => null],
            ['date' => '2026-05-16', 'event_name' => '山田高校同窓会ゴルフコンペ', 'group_count' => 53, 'notes' => null],
            ['date' => '2026-12-29', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-02-06', 'event_name' => null, 'group_count' => 45, 'notes' => null],
            ['date' => '2026-12-31', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-11-16', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-09-14', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-04-16', 'event_name' => null, 'group_count' => 53, 'notes' => null],
            ['date' => '2026-03-12', 'event_name' => null, 'group_count' => 44, 'notes' => null],
            ['date' => '2026-02-14', 'event_name' => null, 'group_count' => 56, 'notes' => null],
            ['date' => '2026-02-05', 'event_name' => null, 'group_count' => 31, 'notes' => null],
            ['date' => '2026-05-24', 'event_name' => 'さつき杯', 'group_count' => 55, 'notes' => null],
            ['date' => '2026-05-25', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-04-26', 'event_name' => null, 'group_count' => 53, 'notes' => null],
            ['date' => '2026-04-21', 'event_name' => null, 'group_count' => 59, 'notes' => null],
            ['date' => '2026-07-27', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-02-04', 'event_name' => null, 'group_count' => 54, 'notes' => null],
            ['date' => '2026-03-26', 'event_name' => null, 'group_count' => 36, 'notes' => null],
            ['date' => '2026-01-05', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-03-15', 'event_name' => '弥生杯', 'group_count' => 51, 'notes' => null],
            ['date' => '2026-10-18', 'event_name' => '神無月杯', 'group_count' => null, 'notes' => null],
            ['date' => '2026-02-24', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-11-22', 'event_name' => '霜月杯', 'group_count' => null, 'notes' => null],
            ['date' => '2026-02-02', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-10-05', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-02-11', 'event_name' => null, 'group_count' => 51, 'notes' => null],
            ['date' => '2026-05-02', 'event_name' => null, 'group_count' => 56, 'notes' => null],
            ['date' => '2026-12-26', 'event_name' => '納会杯', 'group_count' => null, 'notes' => null],
            ['date' => '2026-03-21', 'event_name' => null, 'group_count' => 51, 'notes' => null],
            ['date' => '2026-01-06', 'event_name' => null, 'group_count' => 51, 'notes' => null],
            ['date' => '2026-05-22', 'event_name' => null, 'group_count' => 56, 'notes' => null],
            ['date' => '2026-05-28', 'event_name' => null, 'group_count' => 55, 'notes' => null],
            ['date' => '2026-01-31', 'event_name' => null, 'group_count' => 60, 'notes' => null],
            ['date' => '2026-01-26', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-04-07', 'event_name' => null, 'group_count' => 38, 'notes' => null],
            ['date' => '2026-12-28', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-01-25', 'event_name' => null, 'group_count' => 53, 'notes' => null],
            ['date' => '2026-04-12', 'event_name' => 'クラブ選手権　予選', 'group_count' => 58, 'notes' => null],
            ['date' => '2026-09-28', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-03-05', 'event_name' => null, 'group_count' => 33, 'notes' => null],
            ['date' => '2026-01-24', 'event_name' => null, 'group_count' => 57, 'notes' => null],
            ['date' => '2026-05-27', 'event_name' => null, 'group_count' => 53, 'notes' => null],
            ['date' => '2026-05-18', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-02-18', 'event_name' => null, 'group_count' => 34, 'notes' => null],
            ['date' => '2026-12-07', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-04-03', 'event_name' => null, 'group_count' => 54, 'notes' => null],
            ['date' => '2026-10-17', 'event_name' => '地域感謝デー', 'group_count' => null, 'notes' => null],
            ['date' => '2026-04-08', 'event_name' => null, 'group_count' => 43, 'notes' => null],
            ['date' => '2026-04-27', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-05-03', 'event_name' => null, 'group_count' => 58, 'notes' => null],
            ['date' => '2026-08-02', 'event_name' => '納涼杯', 'group_count' => null, 'notes' => null],
            ['date' => '2026-02-15', 'event_name' => '睦月杯', 'group_count' => 58, 'notes' => null],
            ['date' => '2026-06-01', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-04-19', 'event_name' => 'クラブ選手権　決勝', 'group_count' => 50, 'notes' => null],
            ['date' => '2026-03-14', 'event_name' => '地域感謝デー', 'group_count' => 58, 'notes' => null],
            ['date' => '2026-03-20', 'event_name' => '春分杯', 'group_count' => 57, 'notes' => null],
            ['date' => '2026-02-09', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-01-28', 'event_name' => null, 'group_count' => 40, 'notes' => null],
            ['date' => '2026-07-13', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-12-30', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-01-12', 'event_name' => null, 'group_count' => 53, 'notes' => null],
            ['date' => '2026-01-15', 'event_name' => null, 'group_count' => 47, 'notes' => null],
            ['date' => '2026-10-13', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-08-24', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-03-30', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-06-08', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-11-30', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-11-09', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-01-17', 'event_name' => null, 'group_count' => 54, 'notes' => null],
            ['date' => '2026-09-23', 'event_name' => '秋分杯', 'group_count' => null, 'notes' => null],
            ['date' => '2026-06-07', 'event_name' => '梅雨杯', 'group_count' => null, 'notes' => null],
            ['date' => '2026-01-27', 'event_name' => null, 'group_count' => 34, 'notes' => null],
            ['date' => '2026-03-06', 'event_name' => null, 'group_count' => 50, 'notes' => null],
            ['date' => '2026-08-16', 'event_name' => '盆杯', 'group_count' => null, 'notes' => null],
            ['date' => '2026-05-26', 'event_name' => null, 'group_count' => 36, 'notes' => null],
            ['date' => '2026-03-01', 'event_name' => '梅花杯', 'group_count' => 54, 'notes' => null],
            ['date' => '2026-11-02', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-01-16', 'event_name' => null, 'group_count' => 33, 'notes' => null],
            ['date' => '2026-02-28', 'event_name' => null, 'group_count' => 55, 'notes' => null],
            ['date' => '2026-04-09', 'event_name' => null, 'group_count' => 32, 'notes' => null],
            ['date' => '2026-10-26', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-02-16', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-09-20', 'event_name' => '長月杯', 'group_count' => null, 'notes' => null],
            ['date' => '2026-10-11', 'event_name' => 'クラブ選手権　決勝', 'group_count' => null, 'notes' => null],
            ['date' => '2026-05-01', 'event_name' => null, 'group_count' => 43, 'notes' => null],
            ['date' => '2026-02-01', 'event_name' => null, 'group_count' => 60, 'notes' => null],
            ['date' => '2026-04-17', 'event_name' => null, 'group_count' => 30, 'notes' => null],
            ['date' => '2026-02-12', 'event_name' => null, 'group_count' => 58, 'notes' => null],
            ['date' => '2026-03-23', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-01-09', 'event_name' => null, 'group_count' => 37, 'notes' => null],
            ['date' => '2026-07-21', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-05-23', 'event_name' => null, 'group_count' => 53, 'notes' => null],
            ['date' => '2026-05-07', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-07-26', 'event_name' => 'サマーカップ', 'group_count' => null, 'notes' => null],
            ['date' => '2026-01-02', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-05-11', 'event_name' => '休場日', 'group_count' => null, 'notes' => null],
            ['date' => '2026-07-19', 'event_name' => '文月杯', 'group_count' => null, 'notes' => null],
            ['date' => '2026-04-18', 'event_name' => null, 'group_count' => 54, 'notes' => null],
            ['date' => '2026-05-29', 'event_name' => null, 'group_count' => 31, 'notes' => null],
            ['date' => '2026-04-22', 'event_name' => null, 'group_count' => 50, 'notes' => null],
            ['date' => '2026-03-31', 'event_name' => null, 'group_count' => 50, 'notes' => null],
            ['date' => '2026-02-26', 'event_name' => null, 'group_count' => 51, 'notes' => null],
            ['date' => '2026-04-05', 'event_name' => 'クラブ選手権　予選', 'group_count' => 54, 'notes' => null],
            ['date' => '2026-03-24', 'event_name' => null, 'group_count' => 50, 'notes' => null],
            ['date' => '2026-02-13', 'event_name' => null, 'group_count' => 36, 'notes' => null],
        ];

        foreach ($schedules as $schedule) {
            DailySchedule::create($schedule);
        }
    }
}
